# Generated by Django 3.1.7 on 2021-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
